// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLineProj

#ifndef UI_MANUAL_H
#define UI_MANUAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Manual
extern void ui_Manual_screen_init(void);
extern void ui_Manual_screen_destroy(void);
extern lv_obj_t * ui_Manual;
extern void ui_event_TesterB(lv_event_t * e);
extern lv_obj_t * ui_TesterB;
extern lv_obj_t * ui_TesterBLabel;
extern void ui_event_Ch1Slid(lv_event_t * e);
extern lv_obj_t * ui_Ch1Slid;
extern void ui_event_Ch2Slid(lv_event_t * e);
extern lv_obj_t * ui_Ch2Slid;
extern void ui_event_Ch3Slid(lv_event_t * e);
extern lv_obj_t * ui_Ch3Slid;
extern void ui_event_MaxIDropDown(lv_event_t * e);
extern lv_obj_t * ui_MaxIDropDown;
extern lv_obj_t * ui_Ch3M;
extern lv_obj_t * ui_Ch2M;
extern lv_obj_t * ui_Ch1M;
extern lv_obj_t * ui_MaxI;
extern void ui_event_RelaySw(lv_event_t * e);
extern lv_obj_t * ui_RelaySw;
extern lv_obj_t * ui_RelayLabel;
// CUSTOM VARIABLES
extern uint8_t ch1_power, ch2_power, ch3_power;
extern uint8_t max_I;
extern bool power_switch;

extern bool new_I, new_ch1, new_ch2, new_ch3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

