// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLineProj

#include "ui.h"

lv_obj_t * ui_Manual = NULL;
lv_obj_t * ui_TesterB = NULL;
lv_obj_t * ui_TesterBLabel = NULL;
lv_obj_t * ui_Ch1Slid = NULL;
lv_obj_t * ui_Ch2Slid = NULL;
lv_obj_t * ui_Ch3Slid = NULL;
lv_obj_t * ui_MaxIDropDown = NULL;
lv_obj_t * ui_Ch3M = NULL;
lv_obj_t * ui_Ch2M = NULL;
lv_obj_t * ui_Ch1M = NULL;
lv_obj_t * ui_MaxI = NULL;
lv_obj_t * ui_RelaySw = NULL;
lv_obj_t * ui_RelayLabel = NULL;

uint8_t ch1_power = 0, ch2_power = 0, ch3_power = 0;
uint8_t max_I = 40;
bool power_switch = false;

bool new_I = false, new_ch1 = false, new_ch2 = false, new_ch3 = false;

// event funtions
void ui_event_TesterB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Prog, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Prog_screen_init);
    }
}

void ui_event_Ch1Slid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        (e);
        ch1_power = lv_slider_get_value(ui_Ch1Slid) * 255 / 100;
        new_ch1 = true;
    }
}

void ui_event_Ch2Slid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        (e);
        ch2_power = lv_slider_get_value(ui_Ch2Slid) * 255 / 100;
        new_ch2 = true;
    }
}

void ui_event_Ch3Slid(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        (e);
        ch3_power = lv_slider_get_value(ui_Ch3Slid) * 255 / 100;
        new_ch3 = true;
    }
}

void ui_event_MaxIDropDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        (e);
        uint8_t dropdown_code = 0;
        dropdown_code = lv_dropdown_get_selected(ui_MaxIDropDown);
        switch (dropdown_code) {
            case 0:
                max_I = 40;
                break;
            case 1:
                max_I = 100;
                break;
            case 2:
                max_I = 200;
                break;
            default:
                break;
        }
        new_I = true;
    }
}

void ui_event_RelaySw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
        power_switch = !power_switch;
    }
}

// build funtions

void ui_Manual_screen_init(void)
{
    ui_Manual = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Manual, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TesterB = lv_btn_create(ui_Manual);
    lv_obj_set_width(ui_TesterB, 100);
    lv_obj_set_height(ui_TesterB, 50);
    lv_obj_set_x(ui_TesterB, 162);
    lv_obj_set_y(ui_TesterB, 116);
    lv_obj_set_align(ui_TesterB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TesterB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TesterB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TesterBLabel = lv_label_create(ui_Manual);
    lv_obj_set_width(ui_TesterBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TesterBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TesterBLabel, 160);
    lv_obj_set_y(ui_TesterBLabel, 116);
    lv_obj_set_align(ui_TesterBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TesterBLabel, "Tester");

    ui_Ch1Slid = lv_slider_create(ui_Manual);
    lv_slider_set_value(ui_Ch1Slid, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Ch1Slid) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Ch1Slid, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Ch1Slid, 200);
    lv_obj_set_height(ui_Ch1Slid, 15);
    lv_obj_set_x(ui_Ch1Slid, -50);
    lv_obj_set_y(ui_Ch1Slid, -100);
    lv_obj_set_align(ui_Ch1Slid, LV_ALIGN_CENTER);

    ui_Ch2Slid = lv_slider_create(ui_Manual);
    lv_slider_set_value(ui_Ch2Slid, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Ch2Slid) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Ch2Slid, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Ch2Slid, 200);
    lv_obj_set_height(ui_Ch2Slid, 15);
    lv_obj_set_x(ui_Ch2Slid, -50);
    lv_obj_set_y(ui_Ch2Slid, -25);
    lv_obj_set_align(ui_Ch2Slid, LV_ALIGN_CENTER);

    ui_Ch3Slid = lv_slider_create(ui_Manual);
    lv_slider_set_value(ui_Ch3Slid, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Ch3Slid) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Ch3Slid, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Ch3Slid, 200);
    lv_obj_set_height(ui_Ch3Slid, 15);
    lv_obj_set_x(ui_Ch3Slid, -50);
    lv_obj_set_y(ui_Ch3Slid, 50);
    lv_obj_set_align(ui_Ch3Slid, LV_ALIGN_CENTER);

    ui_MaxIDropDown = lv_dropdown_create(ui_Manual);
    lv_dropdown_set_options(ui_MaxIDropDown, "400 mA\n1 A\n2 A");
    lv_obj_set_width(ui_MaxIDropDown, 150);
    lv_obj_set_height(ui_MaxIDropDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxIDropDown, 150);
    lv_obj_set_y(ui_MaxIDropDown, -50);
    lv_obj_set_align(ui_MaxIDropDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MaxIDropDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Ch3M = lv_label_create(ui_Manual);
    lv_obj_set_width(ui_Ch3M, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch3M, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch3M, -200);
    lv_obj_set_y(ui_Ch3M, 50);
    lv_obj_set_align(ui_Ch3M, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch3M, "Kanal 3");

    ui_Ch2M = lv_label_create(ui_Manual);
    lv_obj_set_width(ui_Ch2M, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch2M, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch2M, -200);
    lv_obj_set_y(ui_Ch2M, -25);
    lv_obj_set_align(ui_Ch2M, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch2M, "Kanal 2");

    ui_Ch1M = lv_label_create(ui_Manual);
    lv_obj_set_width(ui_Ch1M, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch1M, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch1M, -200);
    lv_obj_set_y(ui_Ch1M, -100);
    lv_obj_set_align(ui_Ch1M, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch1M, "Kanal 1");

    ui_MaxI = lv_label_create(ui_Manual);
    lv_obj_set_width(ui_MaxI, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxI, 150);
    lv_obj_set_y(ui_MaxI, -100);
    lv_obj_set_align(ui_MaxI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxI, "Maksymalny prad");

    ui_RelaySw = lv_switch_create(ui_Manual);
    lv_obj_set_width(ui_RelaySw, 50);
    lv_obj_set_height(ui_RelaySw, 25);
    lv_obj_set_x(ui_RelaySw, -130);
    lv_obj_set_y(ui_RelaySw, 120);
    lv_obj_set_align(ui_RelaySw, LV_ALIGN_CENTER);

    ui_RelayLabel = lv_label_create(ui_Manual);
    lv_obj_set_width(ui_RelayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RelayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RelayLabel, -200);
    lv_obj_set_y(ui_RelayLabel, 120);
    lv_obj_set_align(ui_RelayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RelayLabel, "Zasilanie");

    lv_obj_add_event_cb(ui_TesterB, ui_event_TesterB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ch1Slid, ui_event_Ch1Slid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ch2Slid, ui_event_Ch2Slid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Ch3Slid, ui_event_Ch3Slid, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MaxIDropDown, ui_event_MaxIDropDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RelaySw, ui_event_RelaySw, LV_EVENT_ALL, NULL);

}

void ui_Manual_screen_destroy(void)
{
    if(ui_Manual) lv_obj_del(ui_Manual);

    // NULL screen variables
    ui_Manual = NULL;
    ui_TesterB = NULL;
    ui_TesterBLabel = NULL;
    ui_Ch1Slid = NULL;
    ui_Ch2Slid = NULL;
    ui_Ch3Slid = NULL;
    ui_MaxIDropDown = NULL;
    ui_Ch3M = NULL;
    ui_Ch2M = NULL;
    ui_Ch1M = NULL;
    ui_MaxI = NULL;
    ui_RelaySw = NULL;
    ui_RelayLabel = NULL;

}
