// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Stanowisko testowe

#include "ui.h"

lv_obj_t * ui_Prog = NULL;
lv_obj_t * ui_ParamsB = NULL;
lv_obj_t * ui_MainLabel = NULL;
lv_obj_t * ui_PrognTestBut = NULL;
lv_obj_t * ui_ProgBar = NULL;
lv_obj_t * ui_PrognTestLabel = NULL;
lv_obj_t * ui_ParamsBLabel = NULL;
lv_obj_t * ui_ManualB = NULL;
lv_obj_t * ui_ManualBLabel = NULL;
lv_obj_t * ui_ProgBut = NULL;
lv_obj_t * ui_TestBut = NULL;
lv_obj_t * ui_ProgLabel = NULL;
lv_obj_t * ui_TestLabel = NULL;
lv_obj_t * ui_Label = NULL;
lv_obj_t * ui_StopBut = NULL;
lv_obj_t * ui_StopLabel = NULL;

bool p_start = false, t_start = false, pt_start = false;
volatile bool stop_req = false;
// event funtions
void ui_event_ParamsB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Params, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Params_screen_init);
    }
}

void ui_event_PrognTestBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
        pt_start = true;
    }
}

void ui_event_ManualB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Manual, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Manual_screen_init);
    }
}

void ui_event_ProgBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
		p_start = true;
    }
}

void ui_event_TestBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
        t_start = true;
    }
}

void ui_event_StopBut(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
        stop_req = true;
    }
}

// build funtions

void ui_Prog_screen_init(void)
{
    ui_Prog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Prog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ParamsB = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_ParamsB, 100);
    lv_obj_set_height(ui_ParamsB, 50);
    lv_obj_set_x(ui_ParamsB, 162);
    lv_obj_set_y(ui_ParamsB, 116);
    lv_obj_set_align(ui_ParamsB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParamsB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ParamsB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_MainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabel, 4);
    lv_obj_set_y(ui_MainLabel, -120);
    lv_obj_set_align(ui_MainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabel, "QDrive Tester");
    lv_obj_set_style_text_font(ui_MainLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PrognTestBut = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_PrognTestBut, 100);
    lv_obj_set_height(ui_PrognTestBut, 50);
    lv_obj_set_x(ui_PrognTestBut, 5);
    lv_obj_set_y(ui_PrognTestBut, -35);
    lv_obj_set_align(ui_PrognTestBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PrognTestBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PrognTestBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgBar = lv_bar_create(ui_Prog);
    lv_obj_set_width(ui_ProgBar, 350);
    lv_obj_set_height(ui_ProgBar, 15);
    lv_obj_set_x(ui_ProgBar, 5);
    lv_obj_set_y(ui_ProgBar, 30);
    lv_obj_set_align(ui_ProgBar, LV_ALIGN_CENTER);

    ui_PrognTestLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_PrognTestLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrognTestLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrognTestLabel, 4);
    lv_obj_set_y(ui_PrognTestLabel, -35);
    lv_obj_set_align(ui_PrognTestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrognTestLabel, "Program\n       +\n    Test");

    ui_ParamsBLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_ParamsBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamsBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamsBLabel, 161);
    lv_obj_set_y(ui_ParamsBLabel, 116);
    lv_obj_set_align(ui_ParamsBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ParamsBLabel, "Params");

    ui_ManualB = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_ManualB, 100);
    lv_obj_set_height(ui_ManualB, 50);
    lv_obj_set_x(ui_ManualB, -162);
    lv_obj_set_y(ui_ManualB, 116);
    lv_obj_set_align(ui_ManualB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ManualBLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_ManualBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManualBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManualBLabel, -164);
    lv_obj_set_y(ui_ManualBLabel, 116);
    lv_obj_set_align(ui_ManualBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManualBLabel, "Manual");

    ui_ProgBut = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_ProgBut, 100);
    lv_obj_set_height(ui_ProgBut, 50);
    lv_obj_set_x(ui_ProgBut, -145);
    lv_obj_set_y(ui_ProgBut, -35);
    lv_obj_set_align(ui_ProgBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProgBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TestBut = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_TestBut, 100);
    lv_obj_set_height(ui_TestBut, 50);
    lv_obj_set_x(ui_TestBut, 145);
    lv_obj_set_y(ui_TestBut, -35);
    lv_obj_set_align(ui_TestBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TestBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TestBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_ProgLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProgLabel, -146);
    lv_obj_set_y(ui_ProgLabel, -35);
    lv_obj_set_align(ui_ProgLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgLabel, "Programm");

    ui_TestLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_TestLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TestLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TestLabel, 143);
    lv_obj_set_y(ui_TestLabel, -35);
    lv_obj_set_align(ui_TestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TestLabel, "Test");

    ui_Label = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label, 0);
    lv_obj_set_y(ui_Label, 60);
    lv_obj_set_align(ui_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label, "");
    lv_obj_set_style_text_color(ui_Label, lv_color_hex(0xC21919), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopBut = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_StopBut, 120);
    lv_obj_set_height(ui_StopBut, 60);
    lv_obj_set_x(ui_StopBut, 5);
    lv_obj_set_y(ui_StopBut, 116);
    lv_obj_set_align(ui_StopBut, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StopBut, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StopBut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StopBut, lv_color_hex(0x9D0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StopBut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StopLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_StopLabel, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_StopLabel, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_StopLabel, 5);
    lv_obj_set_y(ui_StopLabel, 116);
    lv_obj_set_align(ui_StopLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StopLabel, "STOP");

    lv_obj_add_event_cb(ui_ParamsB, ui_event_ParamsB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PrognTestBut, ui_event_PrognTestBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualB, ui_event_ManualB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProgBut, ui_event_ProgBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TestBut, ui_event_TestBut, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StopBut, ui_event_StopBut, LV_EVENT_ALL, NULL);

}

void ui_Prog_screen_destroy(void)
{
    if(ui_Prog) lv_obj_del(ui_Prog);

    // NULL screen variables
    ui_Prog = NULL;
    ui_ParamsB = NULL;
    ui_MainLabel = NULL;
    ui_PrognTestBut = NULL;
    ui_ProgBar = NULL;
    ui_PrognTestLabel = NULL;
    ui_ParamsBLabel = NULL;
    ui_ManualB = NULL;
    ui_ManualBLabel = NULL;
    ui_ProgBut = NULL;
    ui_TestBut = NULL;
    ui_ProgLabel = NULL;
    ui_TestLabel = NULL;
    ui_Label = NULL;
    ui_StopBut = NULL;
    ui_StopLabel = NULL;
}
