// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLineProj

#include "ui.h"

lv_obj_t * ui_Prog = NULL;
lv_obj_t * ui_ParamsB = NULL;
lv_obj_t * ui_MainLabel = NULL;
lv_obj_t * ui_Start = NULL;
lv_obj_t * ui_ProgBar = NULL;
lv_obj_t * ui_StartLabel = NULL;
lv_obj_t * ui_ParamsBLabel = NULL;
lv_obj_t * ui_ManualB = NULL;
lv_obj_t * ui_ManualBLabel = NULL;

bool p_start = false;
// event funtions
void ui_event_ParamsB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Params, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Params_screen_init);
    }
}

void ui_event_Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
        p_start = true;
    }
}

void ui_event_ManualB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Manual, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Manual_screen_init);
    }
}

// build funtions

void ui_Prog_screen_init(void)
{
    ui_Prog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Prog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ParamsB = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_ParamsB, 100);
    lv_obj_set_height(ui_ParamsB, 50);
    lv_obj_set_x(ui_ParamsB, 162);
    lv_obj_set_y(ui_ParamsB, 116);
    lv_obj_set_align(ui_ParamsB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParamsB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ParamsB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_MainLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabel, 4);
    lv_obj_set_y(ui_MainLabel, -120);
    lv_obj_set_align(ui_MainLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabel, "QDrive Tester");
    lv_obj_set_style_text_font(ui_MainLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Start = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_Start, 100);
    lv_obj_set_height(ui_Start, 50);
    lv_obj_set_x(ui_Start, 5);
    lv_obj_set_y(ui_Start, -35);
    lv_obj_set_align(ui_Start, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Start, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgBar = lv_bar_create(ui_Prog);
    lv_obj_set_width(ui_ProgBar, 150);
    lv_obj_set_height(ui_ProgBar, 10);
    lv_obj_set_x(ui_ProgBar, 8);
    lv_obj_set_y(ui_ProgBar, 47);
    lv_obj_set_align(ui_ProgBar, LV_ALIGN_CENTER);

    ui_StartLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartLabel, 4);
    lv_obj_set_y(ui_StartLabel, -35);
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "Start");

    ui_ParamsBLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_ParamsBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamsBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamsBLabel, 161);
    lv_obj_set_y(ui_ParamsBLabel, 116);
    lv_obj_set_align(ui_ParamsBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ParamsBLabel, "Params");

    ui_ManualB = lv_btn_create(ui_Prog);
    lv_obj_set_width(ui_ManualB, 100);
    lv_obj_set_height(ui_ManualB, 50);
    lv_obj_set_x(ui_ManualB, -162);
    lv_obj_set_y(ui_ManualB, 116);
    lv_obj_set_align(ui_ManualB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ManualBLabel = lv_label_create(ui_Prog);
    lv_obj_set_width(ui_ManualBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ManualBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManualBLabel, -164);
    lv_obj_set_y(ui_ManualBLabel, 116);
    lv_obj_set_align(ui_ManualBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ManualBLabel, "Manual");

    lv_obj_add_event_cb(ui_ParamsB, ui_event_ParamsB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ManualB, ui_event_ManualB, LV_EVENT_ALL, NULL);

}

void ui_Prog_screen_destroy(void)
{
    if(ui_Prog) lv_obj_del(ui_Prog);

    // NULL screen variables
    ui_Prog = NULL;
    ui_ParamsB = NULL;
    ui_MainLabel = NULL;
    ui_Start = NULL;
    ui_ProgBar = NULL;
    ui_StartLabel = NULL;
    ui_ParamsBLabel = NULL;
    ui_ManualB = NULL;
    ui_ManualBLabel = NULL;

}
