// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Stanowisko testowe

#ifndef UI_PROG_H
#define UI_PROG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Prog
extern void ui_Prog_screen_init(void);
extern void ui_Prog_screen_destroy(void);
extern lv_obj_t * ui_Prog;
extern void ui_event_ParamsB(lv_event_t * e);
extern lv_obj_t * ui_ParamsB;
extern lv_obj_t * ui_MainLabel;
extern void ui_event_PrognTestBut(lv_event_t * e);
extern lv_obj_t * ui_PrognTestBut;
extern lv_obj_t * ui_ProgBar;
extern lv_obj_t * ui_PrognTestLabel;
extern lv_obj_t * ui_ParamsBLabel;
extern void ui_event_ManualB(lv_event_t * e);
extern lv_obj_t * ui_ManualB;
extern lv_obj_t * ui_ManualBLabel;
extern void ui_event_ProgBut(lv_event_t * e);
extern lv_obj_t * ui_ProgBut;
extern void ui_event_TestBut(lv_event_t * e);
extern lv_obj_t * ui_TestBut;
extern lv_obj_t * ui_ProgLabel;
extern lv_obj_t * ui_TestLabel;
extern lv_obj_t * ui_Label;
// CUSTOM VARIABLES
extern bool p_start, t_start, pt_start;
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

