// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLineProj

#ifndef UI_PARAMS_H
#define UI_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Params
extern void ui_Params_screen_init(void);
extern void ui_Params_screen_destroy(void);
extern lv_obj_t * ui_Params;
extern void ui_event_ProgB(lv_event_t * e);
extern lv_obj_t * ui_ProgB;
extern lv_obj_t * ui_ProgBLabel;
extern lv_obj_t * ui_VLabel;
extern lv_obj_t * ui_ILabel;
extern lv_obj_t * ui_TLabel;
extern lv_obj_t * ui_Ch1;
extern lv_obj_t * ui_Ch2;
extern lv_obj_t * ui_Ch3;
extern lv_obj_t * ui_MaxTLabel;
extern lv_obj_t * ui_V11;
extern lv_obj_t * ui_I11;
extern lv_obj_t * ui_T11;
extern lv_obj_t * ui_MT1;
extern lv_obj_t * ui_V22;
extern lv_obj_t * ui_I22;
extern lv_obj_t * ui_T22;
extern lv_obj_t * ui_MT2;
extern lv_obj_t * ui_V33;
extern lv_obj_t * ui_I33;
extern lv_obj_t * ui_T33;
extern lv_obj_t * ui_MT3;
extern void ui_event_ParamsSw(lv_event_t * e);
extern lv_obj_t * ui_ParamsSw;
extern lv_obj_t * ui_ParamsSwLabel;
extern lv_obj_t * ui_ErrorLabel;
extern lv_obj_t * ui_Er1;
extern lv_obj_t * ui_Er2;
extern lv_obj_t * ui_Er3;
// CUSTOM VARIABLES
extern bool diagnostic_sw;
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

