// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLineProj

#include "ui.h"

lv_obj_t * ui_Params = NULL;
lv_obj_t * ui_ProgB = NULL;
lv_obj_t * ui_ProgBLabel = NULL;
lv_obj_t * ui_VLabel = NULL;
lv_obj_t * ui_ILabel = NULL;
lv_obj_t * ui_TLabel = NULL;
lv_obj_t * ui_Ch1 = NULL;
lv_obj_t * ui_Ch2 = NULL;
lv_obj_t * ui_Ch3 = NULL;
lv_obj_t * ui_MaxTLabel = NULL;
lv_obj_t * ui_V11 = NULL;
lv_obj_t * ui_I11 = NULL;
lv_obj_t * ui_T11 = NULL;
lv_obj_t * ui_MT1 = NULL;
lv_obj_t * ui_V22 = NULL;
lv_obj_t * ui_I22 = NULL;
lv_obj_t * ui_T22 = NULL;
lv_obj_t * ui_MT2 = NULL;
lv_obj_t * ui_V33 = NULL;
lv_obj_t * ui_I33 = NULL;
lv_obj_t * ui_T33 = NULL;
lv_obj_t * ui_MT3 = NULL;
lv_obj_t * ui_ParamsSw = NULL;
lv_obj_t * ui_ParamsSwLabel = NULL;
lv_obj_t * ui_ErrorLabel = NULL;
lv_obj_t * ui_Er1 = NULL;
lv_obj_t * ui_Er2 = NULL;
lv_obj_t * ui_Er3 = NULL;

bool diagnostic_sw = false;
// event funtions
void ui_event_ProgB(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Prog, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Prog_screen_init);
    }
}

void ui_event_ParamsSw(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        (e);
        diagnostic_sw = !diagnostic_sw;
    }
}

// build funtions

void ui_Params_screen_init(void)
{
    ui_Params = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Params, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgB = lv_btn_create(ui_Params);
    lv_obj_set_width(ui_ProgB, 100);
    lv_obj_set_height(ui_ProgB, 50);
    lv_obj_set_x(ui_ProgB, -165);
    lv_obj_set_y(ui_ProgB, 114);
    lv_obj_set_align(ui_ProgB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProgB, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProgBLabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_ProgBLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProgBLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProgBLabel, -165);
    lv_obj_set_y(ui_ProgBLabel, 114);
    lv_obj_set_align(ui_ProgBLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProgBLabel, "Tester");

    ui_VLabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_VLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VLabel, -180);
    lv_obj_set_y(ui_VLabel, -75);
    lv_obj_set_align(ui_VLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VLabel, "Napiecie");

    ui_ILabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_ILabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ILabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ILabel, -180);
    lv_obj_set_y(ui_ILabel, -50);
    lv_obj_set_align(ui_ILabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ILabel, "Natezenie");

    ui_TLabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_TLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TLabel, -180);
    lv_obj_set_y(ui_TLabel, -25);
    lv_obj_set_align(ui_TLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TLabel, "Temperatura");

    ui_Ch1 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_Ch1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch1, -50);
    lv_obj_set_y(ui_Ch1, -100);
    lv_obj_set_align(ui_Ch1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch1, "Kanal 1");

    ui_Ch2 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_Ch2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch2, 40);
    lv_obj_set_y(ui_Ch2, -100);
    lv_obj_set_align(ui_Ch2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch2, "Kanal 2");

    ui_Ch3 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_Ch3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ch3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Ch3, 130);
    lv_obj_set_y(ui_Ch3, -100);
    lv_obj_set_align(ui_Ch3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ch3, "Kanal 3");

    ui_MaxTLabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_MaxTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxTLabel, -180);
    lv_obj_set_y(ui_MaxTLabel, 0);
    lv_obj_set_align(ui_MaxTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxTLabel, "Max. Temp.");

    ui_V11 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_V11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V11, -50);
    lv_obj_set_y(ui_V11, -75);
    lv_obj_set_align(ui_V11, LV_ALIGN_CENTER);

    ui_I11 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_I11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_I11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_I11, -50);
    lv_obj_set_y(ui_I11, -50);
    lv_obj_set_align(ui_I11, LV_ALIGN_CENTER);

    ui_T11 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_T11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_T11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_T11, -50);
    lv_obj_set_y(ui_T11, -25);
    lv_obj_set_align(ui_T11, LV_ALIGN_CENTER);

    ui_MT1 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_MT1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MT1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MT1, -50);
    lv_obj_set_y(ui_MT1, 0);
    lv_obj_set_align(ui_MT1, LV_ALIGN_CENTER);

    ui_V22 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_V22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V22, 40);
    lv_obj_set_y(ui_V22, -75);
    lv_obj_set_align(ui_V22, LV_ALIGN_CENTER);

    ui_I22 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_I22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_I22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_I22, 40);
    lv_obj_set_y(ui_I22, -50);
    lv_obj_set_align(ui_I22, LV_ALIGN_CENTER);

    ui_T22 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_T22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_T22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_T22, 40);
    lv_obj_set_y(ui_T22, -25);
    lv_obj_set_align(ui_T22, LV_ALIGN_CENTER);

    ui_MT2 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_MT2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MT2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MT2, 40);
    lv_obj_set_y(ui_MT2, 0);
    lv_obj_set_align(ui_MT2, LV_ALIGN_CENTER);

    ui_V33 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_V33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V33, 130);
    lv_obj_set_y(ui_V33, -75);
    lv_obj_set_align(ui_V33, LV_ALIGN_CENTER);

    ui_I33 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_I33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_I33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_I33, 130);
    lv_obj_set_y(ui_I33, -50);
    lv_obj_set_align(ui_I33, LV_ALIGN_CENTER);

    ui_T33 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_T33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_T33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_T33, 130);
    lv_obj_set_y(ui_T33, -25);
    lv_obj_set_align(ui_T33, LV_ALIGN_CENTER);

    ui_MT3 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_MT3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MT3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MT3, 130);
    lv_obj_set_y(ui_MT3, 0);
    lv_obj_set_align(ui_MT3, LV_ALIGN_CENTER);

    ui_ParamsSw = lv_switch_create(ui_Params);
    lv_obj_set_width(ui_ParamsSw, 50);
    lv_obj_set_height(ui_ParamsSw, 25);
    lv_obj_set_x(ui_ParamsSw, -33);
    lv_obj_set_y(ui_ParamsSw, 116);
    lv_obj_set_align(ui_ParamsSw, LV_ALIGN_CENTER);

    ui_ParamsSwLabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_ParamsSwLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ParamsSwLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ParamsSwLabel, 95);
    lv_obj_set_y(ui_ParamsSwLabel, 114);
    lv_obj_set_align(ui_ParamsSwLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ParamsSwLabel, "Aktualizacja parametrow");

    ui_ErrorLabel = lv_label_create(ui_Params);
    lv_obj_set_width(ui_ErrorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ErrorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ErrorLabel, -180);
    lv_obj_set_y(ui_ErrorLabel, 25);
    lv_obj_set_align(ui_ErrorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrorLabel, "Error");

    ui_Er1 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_Er1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Er1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Er1, -50);
    lv_obj_set_y(ui_Er1, 25);
    lv_obj_set_align(ui_Er1, LV_ALIGN_CENTER);

    ui_Er2 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_Er2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Er2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Er2, 40);
    lv_obj_set_y(ui_Er2, 25);
    lv_obj_set_align(ui_Er2, LV_ALIGN_CENTER);

    ui_Er3 = lv_label_create(ui_Params);
    lv_obj_set_width(ui_Er3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Er3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Er3, 130);
    lv_obj_set_y(ui_Er3, 25);
    lv_obj_set_align(ui_Er3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ProgB, ui_event_ProgB, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ParamsSw, ui_event_ParamsSw, LV_EVENT_ALL, NULL);

}

void ui_Params_screen_destroy(void)
{
    if(ui_Params) lv_obj_del(ui_Params);

    // NULL screen variables
    ui_Params = NULL;
    ui_ProgB = NULL;
    ui_ProgBLabel = NULL;
    ui_VLabel = NULL;
    ui_ILabel = NULL;
    ui_TLabel = NULL;
    ui_Ch1 = NULL;
    ui_Ch2 = NULL;
    ui_Ch3 = NULL;
    ui_MaxTLabel = NULL;
    ui_V11 = NULL;
    ui_I11 = NULL;
    ui_T11 = NULL;
    ui_MT1 = NULL;
    ui_V22 = NULL;
    ui_I22 = NULL;
    ui_T22 = NULL;
    ui_MT2 = NULL;
    ui_V33 = NULL;
    ui_I33 = NULL;
    ui_T33 = NULL;
    ui_MT3 = NULL;
    ui_ParamsSw = NULL;
    ui_ParamsSwLabel = NULL;
    ui_ErrorLabel = NULL;
    ui_Er1 = NULL;
    ui_Er2 = NULL;
    ui_Er3 = NULL;

}
