// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLineProj

#ifndef UI_PROG_H
#define UI_PROG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Prog
extern void ui_Prog_screen_init(void);
extern void ui_Prog_screen_destroy(void);
extern lv_obj_t * ui_Prog;
extern void ui_event_ParamsB(lv_event_t * e);
extern lv_obj_t * ui_ParamsB;
extern lv_obj_t * ui_MainLabel;
extern void ui_event_Start(lv_event_t * e);
extern lv_obj_t * ui_Start;
extern lv_obj_t * ui_ProgBar;
extern lv_obj_t * ui_StartLabel;
extern lv_obj_t * ui_ParamsBLabel;
extern void ui_event_ManualB(lv_event_t * e);
extern lv_obj_t * ui_ManualB;
extern lv_obj_t * ui_ManualBLabel;
// CUSTOM VARIABLES
extern bool p_start;
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

